sudo: required

services:
  - docker

script:
  - docker images

env:
    global:
        - DOCKER_ENGINE_VERSION=1.11.2

before_install:

    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_ENGINE_VERSION}-0~trusty

script:
    - docker version
    - docker images

    - MY_NAME=start-points-exercises
    - MY_URL=https://github.com/cyber-dojo/${MY_NAME}.git

    - git clone --depth=1 --branch=master ${MY_URL} ${MY_NAME}

    - docker volume create
             --name=${MY_NAME}
             --label=cyber-dojo-volume=${MY_URL}

    - cid=$(docker run --detach
                       --interactive
                       --net=none
                       --user=root
                       --volume=${MY_NAME}:/data
                       cyberdojo/web:${DOCKER_ENGINE_VERSION} sh)

    - docker cp ${MY_NAME}/. ${cid}:/data

    - docker exec ${cid} sh -c "cd /data && rm -rf .git"
    - docker exec ${cid} sh -c "chown -R cyber-dojo:cyber-dojo /data"
    - docker exec ${cid} sh -c "cd /usr/src/cyber-dojo/cli && ./volume_check.rb /data"
